### ISSUE TITLE
Theme for Android Studio (IntelliJ)

### ISSUE THREAD

**Issue by SalAldana** [zenorocha/dracula-theme#86]
Can someone work on a theme for Android Studio (IntelliJ), I was trying to do it myself but I don't think I'm setting it up correctly. Thanks.

**Comment by zenorocha** [comment]
+1

**Comment by wlisac** [comment]
+1 for IntelliJ

**Comment by zenorocha** [comment]
Here's the color palette if someone wants to jump into this: https://github.com/zenorocha/dracula-theme#color-palette

**Comment by jillesme** [comment]
+1 for IntelliJ

**Comment by zenorocha** [comment]
As described in the README...

> ###### "Are you going to support editor X?"

> I hope so, but I need your help to accomplish that. Since you're using editor X you're probably much more expert on it than me. So feel free to send a pull request based on the Color Palette below.

**Comment by joaoevangelista** [comment]
I did some work on IntelliJ Scheme, but it won't be the same as other editors, example:
The `function` keyword on Javascript get the same color of `var` because they are all mapped as keywords, in that case they will be pink, the same goes for parameter variables, they get the same color on parameter (orange), at editors like Atom, inside the function the color of variable is white. Anyway I did something and I want to share with you guys.

**Javascript**
![js](https://cloud.githubusercontent.com/assets/5256711/11854007/5895a450-a428-11e5-8383-e0d53a985252.png)

**Java**
![java](https://cloud.githubusercontent.com/assets/5256711/11854012/62b57154-a428-11e5-978b-97709825c1d6.png)

**Handlebars**
![hbs](https://cloud.githubusercontent.com/assets/5256711/11854021/6e5dbcfa-a428-11e5-88cf-c2756f1d219f.png)

**CSS**
![css](https://cloud.githubusercontent.com/assets/5256711/11854025/7493b96c-a428-11e5-911f-50b8e1f34ef7.png)

**Kotlin**
![kotlin](https://cloud.githubusercontent.com/assets/5256711/11854059/a5cb49be-a428-11e5-8a09-ae7b908807f8.png)

**Comment by iiNku** [comment]
Is it still under development ? :)

**Comment by joaoevangelista** [comment]
I did some modifications on each language, still not perfect as on Atom since IntelliJ maps are different but [here](https://github.com/joaoevangelista/dracula-intellij) is a WIP 

Also I used some variations of the main pallete as additional colors needed (the main ones still the same)

**Comment by iiNku** [comment]
Thanks @joaoevangelista 

I have a error on Android Studio 1.5.1. Do you want me to create an issue ?

Cannot read scheme Dracula.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

**Comment by joaoevangelista** [comment]
Yes please, also if you have more output message, post it too

**Comment by joaoevangelista** [comment]
Does anyone also disliked the green color as Class and Method's color ? 

![java](https://raw.githubusercontent.com/joaoevangelista/dracula-intellij/master/java.png)

**Comment by joaoevangelista** [comment]
@iiNku Do you know the version of IntelliJ, AS is running under? On help > about might show you the build version

**Comment by zenorocha** [comment]
The JetBrains theme was merged in #148. Could you guys test it out?
